spring:
  application:
    name: eureka-producer

server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    ip-address: 127.0.0.1
    preferIpAddress: true