---
spring:
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config

server:
  port: 8888

eureka:
  instance:
    ip-address: 127.0.0.1
    preferIpAddress: true