spring:
  application:
    name: eureka-consumer

server:
  port: 8888

ribbon-server:
  ribbon:
    eureka:
      enabled: true
      client:
        serviceUrl:
          defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}