spring:
  application:
    name: ribbon-client

server:
  port: 8888

ribbon-server:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8090,localhost:9092,localhost:9999
    ServerListRefreshInterval: 15000