spring:
  application:
    name: eureka-consumer
server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
---
spring:
  profiles: cloud
  application:
    name: ${vcap.application.uris[0]}
eureka:
  instance:
    nonSecurePort: 80
    hostname: ${vcap.application.uris[0]}
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.url}/eureka/
ribbon-server:
  ribbon:
    eureka:
      enabled: true